HP-1671:  new prop `averege_power_consumption`
hiqdev/hipanel-module-server pull request #224
Opened 2023-12-14 21:20 UTC by tafid

2023-12-15 10:33 UTC, SilverFire requested changes

2023-12-15 10:33 UTC, SilverFire commented on src/models/DeviceProperties.php
> +            [['average_power_consumption'], 'string', 'on' => ['set-properties']],
```suggestion
            [['average_power_consumption'], 'number', 'on' => ['set-properties']],
```

2023-12-15 10:33 UTC, SilverFire commented on src/views/hub/view.php
> +                            'label' => 'Average Power Consumption',
i18n is missing

2023-12-15 10:33 UTC, SilverFire commented on src/views/server/modal/hardwareSettings.php
> +            <?= Html::submitButton('Save', ['class' => 'btn btn-success', 'style' => 'display: inline-block']) ?>
i18n is missing

2023-12-19 08:30 UTC, tafid commented on src/models/DeviceProperties.php
> +            'average_power_consumption' => Yii::t('hipanel:server', 'Average Power Consumption'),
Обсудили на дейли

2023-12-19 12:39 UTC, SilverFire approved these changes

2023-12-19 12:43 UTC, merged